#!/bin/sh
DJANGO_MANAGE_VERSION=0.1.1

###############################################################################
# Copyright (c) 2024 Christian Moser . All rights reserved.                   #
#                                                                             #
# Redistribution and use in source and binary forms, with or without          #
# modification, are permitted provided that the following conditions are met: #
#                                                                             #
#   1. Redistributions of source code must retain the above copyright notice, #
#     this list of conditions and the following disclaimer.                   #
#                                                                             #
#   2. Redistributions in binary form must reproduce the above copyright      #
#     notice this list of conditions and the following disclaimer in the      #
#     documentation and/or other materials provided with the distribution.    #
#                                                                             #
#  3. Neither the name of the copyright holder nor the names of its           #
#     contributors may be used to endorse or promote products derived from    #
#     this software without specific prior written permission.                #
#                                                                             #
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" #
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE   #
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE  #
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE   #
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR         #
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF        # 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS    #
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN     #
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)     #
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE  #
# POSSIBILITY OF SUCH DAMAGE.                                                 #
###############################################################################

SELF="`realpath "$0"`"
BASEDIR="`dirname "$SELF"`"

HAVE_PYTHON_VENV="NO"
if [ -n "$DJANGO_VENV" -a -f "${DJANGO_VENV}/bin/activate" ]; then
    HAVE_PYTHON_VENV="YES"
    . "${DJANGO_VENV}/bin/activate"
elif [ -f "${BASEDIR}/python-venv/bin/activate" ]; then
    HAVE_PYTHON_VENV="YES"
    . "${BASEDIR}/python-venv/bin/activate"
elif [ -f "${BASEDIR}/venv/bin/activate" ]; then
    HAVE_PYTHON_VENV="YES"
    . "${BASEDIR}/venv/bin/activate"
elif [ -f "`dirname "${BASEDIR}"`/venv/bin/activate" ]; then
    HAVE_PTHON_VENV="YES"
    . "`dirname "${BASEDIR}"`/venv/bin/activate"
elif [ -f "`dirname "${BASEDIR}"`/python-venv/bin/activate" ]; then
    HAVE_PYTHON_VENV="YES"
    . "`dirname "${BASEDIR}"`/python-venv/bin/activate"
fi

python "${BASEDIR}/manage.py" "$@"

if [ "$HAVE_PYTHON_VENV" = "YES" ]; then
    deactivate
fi
